INSERT INTO DISTRICT (city, name)
VALUES
-- SEOUL (강남구, 종로구, 영등포구 제외)
('SEOUL', '강남구'),
('SEOUL', '종로구'),
('SEOUL', '영등포구'),
('SEOUL', '강동구'),
('SEOUL', '강북구'),
('SEOUL', '강서구'),
('SEOUL', '관악구'),
('SEOUL', '광진구'),
('SEOUL', '구로구'),
('SEOUL', '금천구'),
('SEOUL', '노원구'),
('SEOUL', '도봉구'),
('SEOUL', '동대문구'),
('SEOUL', '동작구'),
('SEOUL', '마포구'),
('SEOUL', '서대문구'),
('SEOUL', '서초구'),
('SEOUL', '성동구'),
('SEOUL', '성북구'),
('SEOUL', '송파구'),
('SEOUL', '양천구'),
('SEOUL', '용산구'),
('SEOUL', '은평구'),
('SEOUL', '중구'),
('SEOUL', '중랑구'),

-- BUSAN
('BUSAN', '중구'),
('BUSAN', '서구'),
('BUSAN', '동구'),
('BUSAN', '영도구'),
('BUSAN', '부산진구'),
('BUSAN', '동래구'),
('BUSAN', '남구'),
('BUSAN', '북구'),
('BUSAN', '해운대구'),
('BUSAN', '사하구'),
('BUSAN', '금정구'),
('BUSAN', '강서구'),
('BUSAN', '연제구'),
('BUSAN', '수영구'),
('BUSAN', '사상구'),
('BUSAN', '기장군'),

-- DAEGU
('DAEGU', '중구'),
('DAEGU', '동구'),
('DAEGU', '서구'),
('DAEGU', '남구'),
('DAEGU', '북구'),
('DAEGU', '수성구'),
('DAEGU', '달서구'),
('DAEGU', '달성군'),

-- INCHEON
('INCHEON', '중구'),
('INCHEON', '동구'),
('INCHEON', '미추홀구'),
('INCHEON', '연수구'),
('INCHEON', '남동구'),
('INCHEON', '부평구'),
('INCHEON', '계양구'),
('INCHEON', '서구'),
('INCHEON', '강화군'),
('INCHEON', '옹진군'),

-- GWANGJU
('GWANGJU', '동구'),
('GWANGJU', '서구'),
('GWANGJU', '남구'),
('GWANGJU', '북구'),
('GWANGJU', '광산구'),

-- DAEJEON
('DAEJEON', '동구'),
('DAEJEON', '중구'),
('DAEJEON', '서구'),
('DAEJEON', '유성구'),
('DAEJEON', '대덕구'),

-- ULSAN
('ULSAN', '중구'),
('ULSAN', '남구'),
('ULSAN', '동구'),
('ULSAN', '북구'),
('ULSAN', '울주군'),

-- SEJONG
('SEJONG', '세종시'),

-- GYEONGGI (수원시 팔달구, 평택시, 이천시 제외)
('GYEONGGI', '수원시 팔달구'),
('GYEONGGI', '평택시'),
('GYEONGGI', '이천시'),
('GYEONGGI', '수원시 장안구'),
('GYEONGGI', '수원시 권선구'),
('GYEONGGI', '수원시 영통구'),
('GYEONGGI', '성남시 수정구'),
('GYEONGGI', '성남시 중원구'),
('GYEONGGI', '성남시 분당구'),
('GYEONGGI', '의정부시'),
('GYEONGGI', '안양시 만안구'),
('GYEONGGI', '안양시 동안구'),
('GYEONGGI', '부천시'),
('GYEONGGI', '광명시'),
('GYEONGGI', '동두천시'),
('GYEONGGI', '안산시 상록구'),
('GYEONGGI', '안산시 단원구'),
('GYEONGGI', '고양시 덕양구'),
('GYEONGGI', '고양시 일산동구'),
('GYEONGGI', '고양시 일산서구'),
('GYEONGGI', '과천시'),
('GYEONGGI', '구리시'),
('GYEONGGI', '남양주시'),
('GYEONGGI', '오산시'),
('GYEONGGI', '시흥시'),
('GYEONGGI', '군포시'),
('GYEONGGI', '의왕시'),
('GYEONGGI', '하남시'),
('GYEONGGI', '용인시 처인구'),
('GYEONGGI', '용인시 기흥구'),
('GYEONGGI', '용인시 수지구'),
('GYEONGGI', '파주시'),
('GYEONGGI', '안성시'),
('GYEONGGI', '김포시'),
('GYEONGGI', '화성시'),
('GYEONGGI', '광주시'),
('GYEONGGI', '양주시'),
('GYEONGGI', '포천시'),
('GYEONGGI', '여주시'),
('GYEONGGI', '연천군'),
('GYEONGGI', '가평군'),
('GYEONGGI', '양평군'),

-- GANGWON
('GANGWON', '춘천시'),
('GANGWON', '원주시'),
('GANGWON', '강릉시'),
('GANGWON', '동해시'),
('GANGWON', '태백시'),
('GANGWON', '속초시'),
('GANGWON', '삼척시'),
('GANGWON', '홍천군'),
('GANGWON', '횡성군'),
('GANGWON', '영월군'),
('GANGWON', '평창군'),
('GANGWON', '정선군'),
('GANGWON', '철원군'),
('GANGWON', '화천군'),
('GANGWON', '양구군'),
('GANGWON', '인제군'),
('GANGWON', '고성군'),
('GANGWON', '양양군'),

-- CHUNGBUK
('CHUNGBUK', '청주시 상당구'),
('CHUNGBUK', '청주시 서원구'),
('CHUNGBUK', '청주시 흥덕구'),
('CHUNGBUK', '청주시 청원구'),
('CHUNGBUK', '충주시'),
('CHUNGBUK', '제천시'),
('CHUNGBUK', '보은군'),
('CHUNGBUK', '옥천군'),
('CHUNGBUK', '영동군'),
('CHUNGBUK', '증평군'),
('CHUNGBUK', '진천군'),
('CHUNGBUK', '괴산군'),
('CHUNGBUK', '음성군'),
('CHUNGBUK', '단양군'),

-- CHUNGNAM
('CHUNGNAM', '천안시 동남구'),
('CHUNGNAM', '천안시 서북구'),
('CHUNGNAM', '공주시'),
('CHUNGNAM', '보령시'),
('CHUNGNAM', '아산시'),
('CHUNGNAM', '서산시'),
('CHUNGNAM', '논산시'),
('CHUNGNAM', '계룡시'),
('CHUNGNAM', '당진시'),
('CHUNGNAM', '금산군'),
('CHUNGNAM', '부여군'),
('CHUNGNAM', '서천군'),
('CHUNGNAM', '청양군'),
('CHUNGNAM', '홍성군'),
('CHUNGNAM', '예산군'),
('CHUNGNAM', '태안군'),

-- JEONBUK
('JEONBUK', '전주시 완산구'),
('JEONBUK', '전주시 덕진구'),
('JEONBUK', '군산시'),
('JEONBUK', '익산시'),
('JEONBUK', '정읍시'),
('JEONBUK', '남원시'),
('JEONBUK', '김제시'),
('JEONBUK', '완주군'),
('JEONBUK', '진안군'),
('JEONBUK', '무주군'),
('JEONBUK', '장수군'),
('JEONBUK', '임실군'),
('JEONBUK', '순창군'),
('JEONBUK', '고창군'),
('JEONBUK', '부안군'),

-- JEONNAM
('JEONNAM', '목포시'),
('JEONNAM', '여수시'),
('JEONNAM', '순천시'),
('JEONNAM', '나주시'),
('JEONNAM', '광양시'),
('JEONNAM', '담양군'),
('JEONNAM', '곡성군'),
('JEONNAM', '구례군'),
('JEONNAM', '고흥군'),
('JEONNAM', '보성군'),
('JEONNAM', '화순군'),
('JEONNAM', '장흥군'),
('JEONNAM', '강진군'),
('JEONNAM', '해남군'),
('JEONNAM', '영암군'),
('JEONNAM', '무안군'),
('JEONNAM', '함평군'),
('JEONNAM', '영광군'),
('JEONNAM', '장성군'),
('JEONNAM', '완도군'),
('JEONNAM', '진도군'),
('JEONNAM', '신안군'),

-- GYEONGBUK
('GYEONGBUK', '포항시 남구'),
('GYEONGBUK', '포항시 북구'),
('GYEONGBUK', '경주시'),
('GYEONGBUK', '김천시'),
('GYEONGBUK', '안동시'),
('GYEONGBUK', '구미시'),
('GYEONGBUK', '영주시'),
('GYEONGBUK', '영천시'),
('GYEONGBUK', '상주시'),
('GYEONGBUK', '문경시'),
('GYEONGBUK', '경산시'),
('GYEONGBUK', '군위군'),
('GYEONGBUK', '의성군'),
('GYEONGBUK', '청송군'),
('GYEONGBUK', '영양군'),
('GYEONGBUK', '영덕군'),
('GYEONGBUK', '청도군'),
('GYEONGBUK', '고령군'),
('GYEONGBUK', '성주군'),
('GYEONGBUK', '칠곡군'),
('GYEONGBUK', '예천군'),
('GYEONGBUK', '봉화군'),
('GYEONGBUK', '울진군'),
('GYEONGBUK', '울릉군'),

-- GYEONGNAM
('GYEONGNAM', '창원시 의창구'),
('GYEONGNAM', '창원시 성산구'),
('GYEONGNAM', '창원시 마산합포구'),
('GYEONGNAM', '창원시 마산회원구'),
('GYEONGNAM', '창원시 진해구'),
('GYEONGNAM', '진주시'),
('GYEONGNAM', '통영시'),
('GYEONGNAM', '사천시'),
('GYEONGNAM', '김해시'),
('GYEONGNAM', '밀양시'),
('GYEONGNAM', '거제시'),
('GYEONGNAM', '양산시'),
('GYEONGNAM', '의령군'),
('GYEONGNAM', '함안군'),
('GYEONGNAM', '창녕군'),
('GYEONGNAM', '고성군'),
('GYEONGNAM', '남해군'),
('GYEONGNAM', '하동군'),
('GYEONGNAM', '산청군'),
('GYEONGNAM', '함양군'),
('GYEONGNAM', '거창군'),
('GYEONGNAM', '합천군'),

-- JEJU
('JEJU', '제주시'),
('JEJU', '서귀포시');